soham4abc/CP_repository

- README.md
> Readme urls updated

- Queries_on_a_Matrix/Queries_on_a_Matrix.cpp
- Queries_on_a_Matrix/Queries_on_a_Matrix.md
https://practice.geeksforgeeks.org/problems/queries-on-a-matrix0443/0
> gfg prob for queries of a matrix

- old_programs/single_linked_list.c
this code has all the single linked list applications
it has insertions and deletions as well
By me
> Singlelinkedlist

- Binary_Tree_to_DLL/Binary_Tree_to_DLL.cpp
- Binary_Tree_to_DLL/Binary_Tree_to_DLL.md
https://practice.geeksforgeeks.org/problems/binary-tree-to-dll/0
> gfg prob to solve bst to dll prob

- Bitwise Operators in C/bitwise_oparators.c
- Bitwise Operators in C/bitwise_operators.md
- Digit Frequency/digit_frequency.c
Create Bitwise Operators in C folder
A problem in HackerRank
https://www.hackerrank.com/challenges/bitwise-operators-in-c/problem?isFullScreen=true
> Create Bitwise Operators in C folder

- Digit Frequency/digit_frequency.md
Make the digit_frequency.md correct
https://www.hackerrank.com/challenges/frequency-of-digits-1/problem?isFullScreen=true
> Make the digit_frequency.md correct

- lets_echo/README.md
- lets_echo/echo.sh
> let's echo

- Boxes through a Tunnel/boxes_through_a_tunnel.c
- Boxes through a Tunnel/boxes_through_a_tunnel.md
I make Boxes through a Tunnel
https://www.hackerrank.com/challenges/too-high-boxes/problem?isFullScreen=true
> Make Boxes through a Tunnel

- loop_in_python/README.md
- loop_in_python/while_loop.py
Task
The provided code stub reads and integer, , from STDIN. For all non-negative integers , print .
Example
The list of non-negative integers that are less than is . Print the square of each number on a separate line.
0
1
4
Input Format
The first and only line contains the integer, .
Constraints
Output Format
Print lines, one corresponding to each .
Sample Input 0
5
Sample Output 0
0
1
4
9
16
> loop in python, while loop

- where_in_sql/README.md
- where_in_sql/city.sql
Query all columns for a city in CITY with the ID 1661.
> SQL query Demo

- Printing Tokens/README.md
- Printing Tokens/printing_tokens.c
I make Printing Tokens
https://www.hackerrank.com/challenges/printing-tokens-/problem?isFullScreen=true
> Make Printing Tokens

- java_formatted_payment/README.md
- java_formatted_payment/formatted_payment.jar
formatted_payment in java
formatted_payment in java
> formatted_payment in java

- ifelseinpython/README.md
- ifelseinpython/ifelseinpython.py
> added python problem for basic if else function

- DiceCombinations/DiceCombinations.cpp
- DiceCombinations/readme.md
> Created DiceCombination File

- QuickSort alogorithm/Quicksort.cpp
- QuickSort alogorithm/Readme.md
Similar to the [Merge Sort](https://www.geeksforgeeks.org/merge-sort/) algorithm, the Quick Sort algorithm is a Divide and Conquer algorithm. It initially selects an element as a pivot element and partitions the given array around the picked pivot. There are many different versions of quickSort that pick pivot in different ways. 
Always pick the first element as a pivot (implemented below).
Always pick the last element as the pivot.
Pick a random element as a pivot.
Pick median as a pivot.
The key process in quickSort is the partition() process. The aim of the partition() function is to receive an array and an element x of the array as a pivot, put x at its correct position in a sorted array and then put all smaller elements (smaller than x) before x, and put all greater elements (greater …
> quicksort using cpp

- arithmaticinshell/README.md
- arithmaticinshell/basicshelloperations.sh
> added shell script to perform basic arithmatic operations

- MemeMan/description.md
- MemeMan/meme_man.py
Added new CP Meme-Man
[Algoleague MemeMan](https://www.algoleague.com/contest/algorithm-training-beginner-set/problem/meme-man/detail)
> Added new CP Meme-Man

- K_Smallest/README.md
- K_Smallest/k_smallest.cpp
_Added a new cp program on finding the k smallest element of an array (using priority queues)_
> added k smallest

- MinimizingCoins/MinimisingCoins.cpp
- MinimizingCoins/readme.md
> added file of MinimizingCoins.cpp, insteresting problem of dp

- DiceCombinations/DiceCombinations.cpp
- Digit Frequency/digit_frequency.c
- K_Smallest/k_smallest.cpp
- java_formatted_payment/formatted_payment.jar
Modified : 
1.  DiceCombinations/DiceCombinations.cpp
2.  Digit Frequency/digit_frequency.c
3.  K_Smallest/k_smallest.cpp
4.  java_formatted_payment/formatted_payment.jar
> Added Combination based CP problems

- Filling Bucket/README.md
- Filling Bucket/fillingBucket.cpp
_Provide an overview..._ added new problem named 'Filling Bucket'
_Add more context to describe your changes..._ It is a dynamic programming based problem.
> Added a problem Filling Bucket (DP problem)

- ValidSudoku/README.md
- ValidSudoku/ValidSudoku.py
Added Valid Sudoku problem with solution in Python
Question link: https://leetcode.com/problems/valid-sudoku/
> added valid sudoku problem

- SumAndDifference/Program.c
- SumAndDifference/Readme.md
_I have done a question to add and subtract integer and floating numbers..._
_I have added a readme file and a program..._
[Example](www.hackerrank.com)
> Sum and Difference
